- name: Install Argo CD on Kubernetes
  hosts: master
  become: yes
  tasks:
    - name: Create a namespace for Argo CD
      kubectl:
        name: argocd
        state: present
        api_version: v1
        kind: Namespace

    - name: Install Argo CD using kubectl
      shell: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Expose Argo CD server via port-forwarding (optional)
      shell: kubectl port-forward svc/argocd-server -n argocd 8080:443
