---
- name: Install K3s and configure worker nodes
  hosts: all
  become: yes
  tasks:
    # Remove conflicting curl-minimal package (if installed)
    - name: Remove conflicting curl-minimal package
      dnf:
        name: curl-minimal
        state: absent
      ignore_errors: yes  # In case the package is not installed, ignore the error

    # Install dependencies (curl, iproute) using dnf
    - name: Install dependencies (curl, iproute) using dnf
      dnf:
        name:
          - curl
          - iproute
        state: present

    # Install K3s Agent on Worker Nodes
    - name: Install K3s Agent on Worker Nodes
      when: inventory_hostname in groups['worker']
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['load_balancer_host'].ansible_host }}:6443 K3S_TOKEN={{ hostvars[groups['master'][0]].k3s_token.stdout }} sh -
      args:
        creates: /usr/local/bin/k3s

    # Enable K3s Agent service on Worker Nodes
    - name: Enable K3s Agent service on Worker Nodes
      systemd:
        name: k3s-agent
        enabled: yes
        state: started

    # Debug the K3s installation token
    - name: Debug the K3s installation token
      debug:
        msg: "The K3s token is: {{ hostvars[groups['master'][0]].k3s_token.stdout }}"
