---
# Install K3s Server on Master Node

- name: Install K3s Server on Master Nodes
  hosts: master
  become: true
  tasks:
    - name: Install K3s Server on Master Node
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Set correct permissions for k3s.yaml
      command: sudo chmod 644 /etc/rancher/k3s/k3s.yaml

- name: Wait for K3s Server to start
  hosts: master
  become: true
  tasks:
    - name: Wait for K3s to start on the Master Node
      wait_for:
        host: "{{ ansible_host }}"
        port: 6443
        delay: 10
        timeout: 300

- name: Generate K3s token
  hosts: master
  become: true
  tasks:
    - name: Generate K3s token for worker nodes
      command: /usr/local/bin/k3s token create
      register: k3s_token

- name: Verify the Cluster Status
  hosts: master
  become: true
  tasks:
    - name: Check the status of K3s cluster
      command: /usr/local/bin/k3s kubectl get nodes
      register: k3s_status

    - name: Show K3s status
      debug:
        var: k3s_status.stdout
