---
- name: Setup K3s Cluster (Master and Worker Nodes)
  hosts: all
  become: yes
  tasks:
    # Ensure curl-minimal is removed first to prevent conflicts
    - name: Remove conflicting curl-minimal package
      dnf:
        name: curl-minimal
        state: absent
      ignore_errors: yes  # In case the package is not installed, ignore the error

    # Install dependencies (curl, iproute) using dnf
    - name: Install dependencies (curl, iproute) using dnf
      dnf:
        name:
          - curl
          - iproute
        state: present

    # Install K3s on Master Node
    - name: Install K3s on Master Node
      when: inventory_hostname in groups['master']
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Enable K3s service on Master
      when: inventory_hostname in groups['master']
      systemd:
        name: k3s
        enabled: yes
        state: started

    # Save K3s Token for Worker Nodes
    - name: Save K3s Token for Worker Nodes
      when: inventory_hostname in groups['master']
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Display K3s Token
      when: inventory_hostname in groups['master']
      debug:
        msg: "The K3
