---
- name: Setup K3s Cluster (Master and Worker Nodes)
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies (curl, iproute) using dnf
      dnf:
        name:
          - curl
          - iproute
        state: present

    - name: Install K3s on Master Node
      when: inventory_hostname in groups['master']
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Enable K3s service on Master
      when: inventory_hostname in groups['master']
      systemd:
        name: k3s
        enabled: yes
        state: started

    - name: Save K3s Token for Worker Nodes
      when: inventory_hostname in groups['master']
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Display K3s Token
      when: inventory_hostname in groups['master']
      debug:
        msg: "The K3s token for worker nodes: {{ k3s_token.stdout }}"

    - name: Copy K3s Kubeconfig to Local Machine
      when: inventory_hostname in groups['master']
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ansible/k3s_master_kubeconfig
        remote_src: yes
        mode: '0644'

    - name: Install K3s Agent on Worker Nodes
      when: inventory_hostname in groups['worker']
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['master'][ansible_host] }}:6443 K3S_TOKEN={{ hostvars['master']['k3s_token']['stdout'] }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Enable K3s Agent service on Worker Nodes
      when: inventory_hostname in groups['worker']
      systemd:
        name: k3s-agent
        enabled: yes
        state: started
