---
- name: Install K3s on Master Nodes
  hosts: master
  become: true
  tasks:
    - name: Install K3s Server on Master Node
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Set correct permissions for k3s.yaml
      command: sudo chmod 644 /etc/rancher/k3s/k3s.yaml

- name: Wait for K3s Server to Start on Master Node
  hosts: master
  become: true
  tasks:
    - name: Wait for K3s to start on the Master Node
      wait_for:
        host: "{{ ansible_host }}"
        port: 6443
        delay: 10
        timeout: 300

- name: Generate K3s Token for Worker Nodes
  hosts: master
  become: true
  tasks:
    - name: Generate K3s token for worker nodes
      command: /usr/local/bin/k3s token create
      register: k3s_token

- name: Install K3s Agent on Worker Nodes
  hosts: worker
  become: true
  vars:
    k3s_master_ip: "{{ hostvars[groups['master'][0]].ansible_host }}"  # Dynamically get the first master IP from inventory
    k3s_token: "{{ hostvars['master'].k3s_token.stdout }}"  # Get the token generated on master node

  tasks:
    - name: Install K3s Agent on Worker Node
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL="https://{{ k3s_master_ip }}:6443" K3S_TOKEN="{{ k3s_token }}" sh -
      environment:
        K3S_TOKEN: "{{ k3s_token }}"
        K3S_URL: "https://{{ k3s_master_ip }}:6443"
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure k3s-agent service is started
      service:
        name: k3s-agent
        state: started
        enabled: yes

- name: Verify Worker Node Joins Cluster
  hosts: worker
  become: true
  tasks:
    - name: Check K3s node status
      command: /usr/local/bin/k3s kubectl get nodes
      register: k3s_node_status

    - name: Show Worker Node Status
      debug:
        var: k3s_node_status.stdout

- name: Verify the Cluster Status
  hosts: master
  become: true
  tasks:
    - name: Check the status of K3s cluster
      command: /usr/local/bin/k3s kubectl get nodes
      register: k3s_status

    - name: Show K3s status
      debug:
        var: k3s_status.stdout
