
name: Terraform and Ansible Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false

      # Step 3: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate Terraform Configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Plan Terraform Changes
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 7: Apply Terraform Changes
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Only apply on the main branch
        run: terraform apply -auto-approve tfplan

      # Step 8: Capture Terraform Outputs and write to file
      - name: Fetch Terraform Outputs and write to file
        run: |
          echo "Fetching Terraform outputs..."
          
          # Fetching the IPs directly (No JSON Parsing)
          MASTER_IPS=$(terraform output -raw master_node_ip || echo "")
          WORKER_IPS=$(terraform output -raw worker_node_ips || echo "")
          ANSIBLE_IP=$(terraform output -raw ansible_node_ip || echo "")
          MASTER_PRIVATE_IP=$(terraform output -raw master_private_ip || echo "")
          WORKER_PRIVATE_IP=$(terraform output -raw worker_private_ips || echo "")

          # Check if any of the outputs are missing or empty
          if [ -z "$MASTER_IPS" ] || [ -z "$WORKER_IPS" ] || [ -z "$ANSIBLE_IP" ] || [ -z "$MASTER_PRIVATE_IP" ] || [ -z "$WORKER_PRIVATE_IP" ] ; then
            echo "Error: One or more Terraform outputs are missing or empty."
            exit 1
          fi

          # Write the IPs to a file (this file will be used by the ansible job)
          echo "MASTER_IPS=$MASTER_IPS" > terraform_output.txt
          echo "WORKER_IPS=$WORKER_IPS" >> terraform_output.txt
          echo "ANSIBLE_IP=$ANSIBLE_IP" >> terraform_output.txt
          echo "MASTER_PRIVATE_IP=$MASTER_PRIVATE_IP" >> terraform_output.txt
          echo "WORKER_PRIVATE_IP=$WORKER_PRIVATE_IP" >> terraform_output.txt

          # Print the IPs to the log
          echo "Master IPs: $MASTER_IPS"
          echo "Worker IPs: $WORKER_IPS"
          echo "Ansible IP: $ANSIBLE_IP"
          echo "Private_Master_IP: $MASTER_PRIVATE_IP"
          echo "Private_Worker_IP: $WORKER_PRIVATE_IP"
          

      # Upload the file as an artifact so it can be accessed in the next job
      - name: Upload Terraform Output File
        uses: actions/upload-artifact@v4
        with:
          name: terraform_output_file
          path: terraform_output.txt

  ansible:
    runs-on: ubuntu-latest
    needs: terraform  # This will ensure it waits for the terraform job

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install sshpass
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # Step 3: Download the Terraform output file
      - name: Download Terraform Output File
        uses: actions/download-artifact@v4
        with:
          name: terraform_output_file

      # Step 4: Read the IPs from the file
      - name: Read IPs from the file
        run: |
          # Read IPs from the file using `cat` and `cut` to extract values
          MASTER_IPS=$(cat terraform_output.txt | grep "MASTER_IPS" | cut -d'=' -f2)
          WORKER_IPS=$(cat terraform_output.txt | grep "WORKER_IPS" | cut -d'=' -f2)
          ANSIBLE_IP=$(cat terraform_output.txt | grep "ANSIBLE_IP" | cut -d'=' -f2)
          MASTER_PRIVATE_IP=$(cat terraform_output.txt | grep "MASTER_PRIVATE_IP" | cut -d'=' -f2)
          WORKER_PRIVATE_IP=$(cat terraform_output.txt | grep "WORKER_PRIVATE_IP" | cut -d'=' -f2)
          
          
          

          # Debugging to ensure the variables are set correctly
          echo "MASTER_IPS: $MASTER_IPS"
          echo "WORKER_IPS: $WORKER_IPS"
          echo "ANSIBLE_IP: $ANSIBLE_IP"
          echo "MASTER_PRIVATE_IP: $MASTER_PRIVATE_IP
          echo "WORKER_PRIVATE_IP: $WORKER_PRIVATE_IP
          

      # Step 5: Configure SSH Access
      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 6: Set up SSH Keys on Ansible Control Node
      - name: Set up SSH Keys on Ansible Control Node
        run: |
          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh
          MASTER_IPS=$(cat terraform_output.txt | grep "MASTER_IPS" | cut -d'=' -f2)
          WORKER_IPS=$(cat terraform_output.txt | grep "WORKER_IPS" | cut -d'=' -f2)
          ANSIBLE_IP=$(cat terraform_output.txt | grep "ANSIBLE_IP" | cut -d'=' -f2)
          
          # Create the SSH private key file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Generate a new key pair for SSH access
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${ANSIBLE_IP} << 'EOF'
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa_ansible -N "" -q
          #PUBLIC_KEY=$(cat ~/.ssh/id_rsa_ansible.pub)
          cat ~/.ssh/id_rsa_ansible.pub > ~/ansible_public_key.pub
          EOF
          
          # Copy the public key back to the local machine
           scp -i ~/.ssh/id_rsa ubuntu@${ANSIBLE_IP}:~/ansible_public_key.pub ./ansible_public_key.pub

          # Step 2: Copy the public key file to each master and worker node
          copy_key_to_node() {
          NODE_IP=$1
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./ansible_public_key.pub ubuntu@$NODE_IP:~/ansible_public_key.pub
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@$NODE_IP << 'EOF'
          mkdir -p ~/.ssh
          cat ~/ansible_public_key.pub >> ~/.ssh/authorized_keys
          rm ~/ansible_public_key.pub
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          EOF
          }

          # Step 3: Loop through the master and worker IPs and copy the key
          for master in $(echo "$MASTER_IPS" | tr "," "\n"); do
          copy_key_to_node $master
          done

          for worker in $(echo "$WORKER_IPS" | tr "," "\n"); do
          copy_key_to_node $worker
          done
      # Step 7: Create Ansible Inventory
      - name: Create Ansible Inventory
        run: |
          MASTER_IPS=$(cat terraform_output.txt | grep "MASTER_IPS" | cut -d'=' -f2)
          WORKER_IPS=$(cat terraform_output.txt | grep "WORKER_IPS" | cut -d'=' -f2)
          ANSIBLE_IP=$(cat terraform_output.txt | grep "ANSIBLE_IP" | cut -d'=' -f2)
          MASTER_PRIVATE_IP=$(cat terraform_output.txt | grep "MASTER_PRIVATE_IP" | cut -d'=' -f2)
          WORKER_PRIVATE_IP=$(cat terraform_output.txt | grep "WORKER_PRIVATE_IP" | cut -d'=' -f2)
          scp -i ~/.ssh/id_rsa terraform_output.txt ubuntu@${ANSIBLE_IP}:~/terraform_output.txt
          
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${ANSIBLE_IP} << 'EOF'
          MASTER_IPS=$(cat ~/terraform_output.txt | grep "MASTER_IPS" | cut -d'=' -f2)
          WORKER_IPS=$(cat ~/terraform_output.txt | grep "WORKER_IPS" | cut -d'=' -f2)
          MASTER_PRIVATE_IP=$(cat terraform_output.txt | grep "MASTER_PRIVATE_IP" | cut -d'=' -f2)
          
          echo "[master]" > ~/inventory.ini
          #echo "\$MASTER_IPS ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa_ansible \
          #ansible_ssh_common_args='-o StrictHostKeyChecking=no' private_ip=\$MASTER_PRIVATE_IP" >> ~/inventory.ini 
          echo "$MASTER_IPS ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa_ansible ansible_ssh_common_args='-o StrictHostKeyChecking=no' private_ip=$MASTER_PRIVATE_IP" >> ~/inventory.ini 
          
          echo "[worker]" >> ~/inventory.ini
          for worker in $(echo "$WORKER_IPS" | tr "," "\n"); do
            echo "$worker ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa_ansible ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ~/inventory.ini
          done
          EOF

      # Step 8: Run Ansible Playbooks
      - name: Run Ansible Playbooks
        run: |
          ANSIBLE_IP=$(cat terraform_output.txt | grep "ANSIBLE_IP" | cut -d'=' -f2)
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${ANSIBLE_IP} << 'EOF'
          mkdir -p /tmp/repo
          cd /tmp/repo
          sudo apt update -y
          sudo apt install -y ansible  # Replace with your desired version
          sudo apt install -y git
          ansible-galaxy collection install community.kubernetes
          /usr/bin/git clone https://github.com/ma914372/Demo.git /tmp/repo
          /usr/bin/ansible-playbook -i ~/inventory.ini /tmp/repo/kubernetes.yaml
          /usr/bin/ansible-playbook -i ~/inventory.ini /tmp/repo/argocd.yaml
